# Pod simple, de un nginx que hace usa en pvc para persistir la home.
apiVersion: v1
kind: Pod
metadata:
 name: mypod
spec:
 containers:
   - name: nginxpvcejemplo
     image: nginx
     volumeMounts:
     - mountPath: "/usr/share/nginx/html"
       name: mypd
 volumes:
   - name: mypd
     persistentVolumeClaim:
       claimName: myclaim