apiVersion: v1
kind: PersistentVolume
metadata:
  name: heimdall-pv-nfs   # < name of the persistent volume ("pv") in kubenetes
  namespace: heimdall     # < namespace where place the pv
spec:
  storageClassName: ""
  capacity:
    storage: 1Gi          # < max. size we reserve for the pv
  accessModes:
    - ReadWriteMany       # < Multiple pods can write to storage 
  persistentVolumeReclaimPolicy: Retain   # < The persistent volume can reclaimed 
  mountOptions:           # < Mount options specific for nfs 4.1, remove if version < 4.1 nfs server is used
    - hard
    - nfsvers=4.1
  nfs:
    server: 192.168.41.85         # < IP number of your NFS server
    path: "/nfsdata/heimdall" # < Name of your NFS share with subfolder
    readOnly: false