apiVersion: v1
kind: Service
metadata:
  name: traefik
#  annotations:
#    metallb.universe.tf/address-pool: default
spec:
  ports:
  - port: 80
    targetPort: 80
    name: http
  - port: 443
    targetPort: 443
    name: https
  - port: 8080
    targetPort: 8080
    name: admin
  selector:
    app: traefik
  type: LoadBalancer
