apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-route
  namespace: default
spec:
  entryPoints:
    - web
  routes:
  - match: Host(`pepe.domain.com`)
    kind: Rule
    services:
    - name: nginx-service
      port: 80

