# Ejemplo de un pod nginx, para ser usado con traefik.
kind: Deployment
apiVersion: apps/v1
metadata:
   name: nginx2
   namespace: default
spec:
   replicas: 1
   selector:
      matchLabels:
         app: nginx2
   template:
      metadata:
         labels:
            app: nginx2
      spec:
         containers:
            - name: nginx2
              image: nginx:latest
              volumeMounts:
              - mountPath: /usr/share/nginx/html
                name: nginx-data
         volumes:
         - name: nginx-data
           hostPath:
              path: /mnt/data/nginx-data
              type: Directory

---
apiVersion: v1
kind: Service
metadata:
   name: nginx2
   labels:
      app: nginx2
spec:
   ports:
      - port: 80
        name: nginx2
   selector:
      app: nginx2
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: nginx2-route
  namespace: default
spec:
  entryPoints:  
    - web
  routes:
  - match: Host(`nginx2.domain.com`)
    kind: Rule
    services:
    - name: nginx2
      port: 80
#  tls:
#      certResolver: myresolver
